### ISSUE TITLE
Allow for custom "white" and "black" colors

### ISSUE THREAD

**Issue by VinSpee** [ben-eb/postcss-color-yiq#1]
It'd be awesome to be able to specify custom colors for "white" and "black", for instance:

``` js
postcss().use(yiq({
    darkColor: "#222222",
    lightColor: "#efefef"
  }))
```

then, possibly after that, It would be great to actually find the real contrast ratio between the custom colors and the background, and choose correctly.

Any thoughts on something like this?

**Comment by ben-eb** [comment]
Sure, this looks like low hanging fruit to me. PR welcome. :smile:

**Comment by VinSpee** [comment]
Will do - it will be my first whack at a PostCSS plugin code base - will require a close review :-)

(null)

**Comment by ben-eb** [comment]
Fixed in https://github.com/ben-eb/postcss-color-yiq/commit/6621e21d34f24ab982ccadb88fcaa81a783ecc2c.
